######################################################################
# Automatically generated by qmake (3.0) ?r. kwi 16 00:22:57 2014
######################################################################

TEMPLATE = app
TARGET = nefJPGConverter
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
